In [509]:
import numpy as np

Datatypes and Attributes

In [510]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [511]:
type(a1)

numpy.ndarray

In [512]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [513]:
type(a2)

numpy.ndarray

In [514]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [515]:
a1.shape

(3,)

In [516]:
a2.shape

(2, 3)

In [517]:
a3.shape


(2, 3, 3)

In [518]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [519]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [520]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [521]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [522]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [523]:
import pandas as pd

In [524]:
df = pd.DataFrame(a2)

In [525]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [526]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [527]:
sample_array.dtype

dtype('int64')

In [528]:
ones = np.ones((2, 3))

In [529]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [530]:
ones.dtype

dtype('float64')

In [531]:
type(ones)

numpy.ndarray

In [532]:
zeros = np.zeros((2, 3))

In [533]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [534]:
range_array = np.arange(0, 10, 2)

In [535]:
range_array

array([0, 2, 4, 6, 8])

In [536]:
random_array = np.random.randint(0, 10, size=(3,5))

In [537]:
random_array

array([[4, 6, 8, 0, 6],
       [8, 7, 8, 5, 0],
       [1, 8, 4, 9, 6]])

In [538]:
random_array.size

15

In [539]:
random_array.shape

(3, 5)

In [540]:
np.random.random((5, 3))

array([[0.87759705, 0.08952686, 0.15970587],
       [0.40431679, 0.33437058, 0.44957863],
       [0.61185953, 0.70279548, 0.27516302],
       [0.04430594, 0.15315687, 0.99810767],
       [0.97101098, 0.06916945, 0.03940035]])

In [541]:
random_array.shape

(3, 5)

In [542]:
np.random.seed()

In [543]:
random_array_3 = np.random.rand(5, 3)

In [544]:
random_array_3

array([[0.28253535, 0.92248951, 0.5197279 ],
       [0.51576655, 0.32486834, 0.13826315],
       [0.68454012, 0.75145342, 0.24339927],
       [0.03763115, 0.34349661, 0.28211752],
       [0.31861117, 0.24689432, 0.43994998]])

In [545]:
random_array_3.size

15

In [546]:
random_array_3.shape

(5, 3)

In [547]:
type(random_array_3)

numpy.ndarray

In [548]:
# np.random.seed()
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4


array([[4, 4, 4],
       [4, 3, 9],
       [9, 9, 2],
       [7, 6, 0],
       [4, 5, 4]])

In [549]:
random_array_4.shape

(5, 3)

In [550]:
random_array_4.size

15

In [551]:
random_array_5 = np.random.random((5, 3))

In [552]:
random_array_5

array([[0.45598332, 0.11271032, 0.47836796],
       [0.41679404, 0.03351591, 0.79174594],
       [0.18922578, 0.67830384, 0.64633662],
       [0.76198662, 0.1343883 , 0.22217838],
       [0.50789636, 0.50916196, 0.81219058]])

In [553]:
random_array_5.shape

(5, 3)

In [554]:
random_array_5 = np.random.random((5, 3))

Viewing arrays

In [555]:
## viewing arrays and matrices 

In [556]:
 np.unique(random_array_4)

array([0, 2, 3, 4, 5, 6, 7, 9])

In [557]:
random_array_99 = np.random.randint(999, size=(100,10))

In [558]:
random_array_99

array([[753, 964,  19, 208, 360, 134, 341, 302, 654,  68],
       [683,   4, 598, 481, 746, 819, 531, 542, 398, 271],
       [185, 307, 591, 211, 732,  11, 898, 555, 931, 137],
       [959, 238, 370, 235, 508, 618, 883, 405, 120, 346],
       [558, 270, 727, 357,  41, 930, 128, 811, 436, 606],
       [691, 208,  30, 530, 110, 553, 249, 429,  50, 506],
       [889, 776,  56, 914, 180, 877, 566, 297, 353, 857],
       [571, 207, 154,  32, 732,  50, 242, 164, 126, 253],
       [856, 901, 964, 964, 128, 261, 935, 382, 129, 466],
       [311, 789, 867, 803, 371, 811, 221, 398, 968, 298],
       [995, 321, 953, 562, 301, 103, 304, 926,  35, 873],
       [750, 199, 930, 371, 982, 850, 997,  20,  63,  65],
       [292, 931, 168, 326,  21, 553, 371, 569, 587, 710],
       [271, 367, 408, 256, 673, 746, 133,  97, 180, 132],
       [517, 137, 744, 224, 450, 637, 620, 924, 411, 705],
       [976, 228,  74, 398,  27, 701, 562, 202, 892, 110],
       [530, 403, 673, 318, 374, 378, 509, 924, 359, 684

In [559]:
np.unique(random_array_99())

TypeError: 'numpy.ndarray' object is not callable

In [560]:
np.unique([1,2,3,4,4,4,6])

array([1, 2, 3, 4, 6])

In [561]:
a1[0]

1

In [562]:
a3.shape

(2, 3, 3)

In [563]:
random_array_99.shape

(100, 10)

In [564]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [565]:
a2[1]

array([4. , 5. , 6.5])

In [566]:
 a4 = np.random.randint(10, size=(2,3,4,5))

In [567]:
a4

array([[[[0, 6, 0, 1, 6],
         [7, 3, 0, 3, 5],
         [3, 7, 8, 7, 9],
         [1, 3, 3, 0, 7]],

        [[3, 9, 6, 6, 9],
         [8, 9, 5, 5, 7],
         [5, 8, 2, 0, 8],
         [6, 7, 3, 3, 8]],

        [[6, 8, 2, 9, 1],
         [7, 2, 1, 8, 1],
         [5, 1, 3, 8, 1],
         [7, 4, 4, 5, 4]]],


       [[[6, 8, 1, 5, 4],
         [3, 7, 5, 9, 9],
         [8, 7, 4, 8, 1],
         [3, 2, 5, 7, 1]],

        [[2, 3, 4, 9, 4],
         [6, 7, 5, 2, 4],
         [5, 3, 2, 0, 2],
         [2, 0, 5, 3, 7]],

        [[0, 5, 5, 3, 9],
         [3, 1, 6, 4, 6],
         [0, 1, 8, 4, 9],
         [1, 3, 4, 6, 8]]]])

In [568]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [569]:
a4[:, :, :, :1]

array([[[[0],
         [7],
         [3],
         [1]],

        [[3],
         [8],
         [5],
         [6]],

        [[6],
         [7],
         [5],
         [7]]],


       [[[6],
         [3],
         [8],
         [3]],

        [[2],
         [6],
         [5],
         [2]],

        [[0],
         [3],
         [0],
         [1]]]])

In [570]:
#4. manipulating and comparing arrays

arithmetic 

In [571]:
a1 + ones


array([[2., 3., 4.],
       [2., 3., 4.]])

In [572]:
ones = np.ones(3)

In [573]:
ones

array([1., 1., 1.])

In [574]:
a1 + ones

array([2., 3., 4.])

In [575]:
a1 - ones

array([0., 1., 2.])

In [576]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [577]:
a1

array([1, 2, 3])

In [578]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [579]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [580]:
np.reshape()

TypeError: _reshape_dispatcher() missing 2 required positional arguments: 'a' and 'newshape'

In [581]:
a1 / ones

array([1., 2., 3.])

In [582]:
a1 // a2

array([[1., 1., 0.],
       [0., 0., 0.]])

In [583]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [584]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [585]:
listy_list = [1,2,3]

In [586]:
type(listy_list)

list

In [587]:
sum(listy_list)

6

In [588]:
np.sum(a1)

6

In [594]:
massive_array = np.random.random(100000)

In [593]:
massive_array[:10]

array([8.44425111e-01, 7.02781465e-01, 6.58211990e-01, 1.66222802e-03,
       3.85199510e-02, 7.88458332e-01, 5.85235696e-01, 3.27076664e-04,
       1.52572846e-01, 6.46793991e-01])

In [591]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

14 ms ± 190 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
28.6 µs ± 665 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [595]:
np.min(a2)

1.0

In [596]:
np.var(a2)

3.3222222222222224