In [56]:
import numpy as np

Datatypes and Attributes

In [57]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [58]:
type(a1)

numpy.ndarray

In [59]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [60]:
type(a2)

numpy.ndarray

In [61]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [62]:
a1.shape

(3,)

In [63]:
a2.shape

(2, 3)

In [64]:
a3.shape


(2, 3, 3)

In [65]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [66]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [67]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [68]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [69]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [70]:
import pandas as pd

In [71]:
df = pd.DataFrame(a2)

In [72]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [73]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [74]:
sample_array.dtype

dtype('int64')

In [75]:
ones = np.ones((2, 3))

In [76]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [77]:
ones.dtype

dtype('float64')

In [78]:
type(ones)

numpy.ndarray

In [79]:
zeros = np.zeros((2, 3))

In [80]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [81]:
range_array = np.arange(0, 10, 2)

In [82]:
range_array

array([0, 2, 4, 6, 8])

In [83]:
random_array = np.random.randint(0, 10, size=(3,5))

In [84]:
random_array

array([[6, 2, 3, 7, 0],
       [8, 6, 1, 2, 2],
       [6, 4, 9, 0, 6]])

In [85]:
random_array.size

15

In [86]:
random_array.shape

(3, 5)

In [87]:
np.random.random((5, 3))

array([[0.19172076, 0.88240521, 0.25703336],
       [0.70650238, 0.56046749, 0.5694567 ],
       [0.77946512, 0.81516374, 0.97923977],
       [0.68315062, 0.91965347, 0.79350236],
       [0.67010653, 0.00807491, 0.65220219]])

In [88]:
random_array.shape

(3, 5)

In [89]:
np.random.seed()

In [90]:
random_array_3 = np.random.rand(5, 3)

In [91]:
random_array_3

array([[0.82625565, 0.10822063, 0.9304474 ],
       [0.90256751, 0.20815456, 0.75933989],
       [0.48683033, 0.96066304, 0.79104159],
       [0.72715623, 0.63347353, 0.92336916],
       [0.71120856, 0.09398726, 0.04355432]])

In [92]:
random_array_3.size

15

In [93]:
random_array_3.shape

(5, 3)

In [94]:
type(random_array_3)

numpy.ndarray

In [95]:
# np.random.seed()
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4


array([[6, 4, 9],
       [1, 1, 9],
       [6, 6, 6],
       [9, 2, 2],
       [5, 3, 8]])

In [96]:
random_array_4.shape

(5, 3)

In [97]:
random_array_4.size

15

In [98]:
random_array_5 = np.random.random((5, 3))

In [99]:
random_array_5

array([[0.37283758, 0.63710017, 0.57292473],
       [0.32672992, 0.88802398, 0.12646667],
       [0.48170389, 0.36100372, 0.06016009],
       [0.02397983, 0.52632323, 0.51669609],
       [0.21327105, 0.01327629, 0.4986959 ]])

In [100]:
random_array_5.shape

(5, 3)

In [101]:
random_array_5 = np.random.random((5, 3))

Viewing arrays

In [102]:
## viewing arrays and matrices 

In [103]:
 np.unique(random_array_4)

array([1, 2, 3, 4, 5, 6, 8, 9])

In [104]:
random_array_99 = np.random.randint(999, size=(10,10))

In [105]:
random_array_99

array([[805, 552, 416, 134, 167, 256, 499, 752, 906, 335],
       [452, 289,  43, 577, 192,  55, 587, 361, 844, 995],
       [882, 129, 913, 388, 923, 304, 545, 987, 277,  41],
       [572, 522, 135, 792, 203, 345, 115, 588, 608, 890],
       [407, 153, 487, 498,  82,  90, 962, 531, 950, 531],
       [787, 491, 350, 768, 124, 561, 997, 120, 232, 813],
       [786, 328, 809, 128, 107, 523, 722, 328, 626, 744],
       [669, 889, 331, 458, 342, 936, 227, 174, 654, 922],
       [887, 139, 849, 979, 221, 659, 535, 829, 197, 625],
       [  4,  25, 478, 804, 156, 159,  75, 224,   3, 730]])

In [106]:
np.unique(random_array_99())

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
np.unique([1,2,3,4,4,4,6])

In [ ]:
a1[0]

In [ ]:
a3.shape

In [ ]:
random_array_99.shape

In [ ]:
a3

In [ ]:
a2[1]

In [ ]:
 a4 = np.random.randint(10, size=(2,3,4,5))

In [ ]:
a4

In [ ]:
a4.shape, a4.ndim

In [ ]:
a4[:, :, :, :1]

In [ ]:
#4. manipulating and comparing arrays

arithmetic 

In [ ]:
a1 + ones


In [ ]:
ones = np.ones(3)

In [ ]:
ones

In [ ]:
a1 + ones

In [ ]:
a1 - ones

In [ ]:
a1 * a2

In [ ]:
a1

In [ ]:
a2

In [ ]:
a2 * a3

In [ ]:
np.reshape()

In [ ]:
a1 / ones

In [ ]:
a1 // a2

In [114]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [ ]:
np.log(a1)

In [ ]:
listy_list = [1,2,3]

In [ ]:
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
np.sum(a1)

In [ ]:
massive_array = np.random.random(100000)

In [ ]:
massive_array[:10]

In [ ]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

In [ ]:
np.min(a2)

In [ ]:
np.var(a2)

In [107]:
a2.T.shape

(3, 2)

In [108]:
a2.T


array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [109]:
a2.reshape()

TypeError: reshape() takes exactly 1 argument (0 given)

In [112]:
a2.reshape(2, 3, 1).shape

(2, 3, 1)

In [113]:
a2.shape


(2, 3)

In [115]:
a2_reshape = a2.reshape(2,3,1)

In [116]:
a2_reshape


array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [117]:
a2_reshape.size

6

In [118]:
a2_reshape.shape

(2, 3, 1)

In [119]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [120]:
# how to transpose a matrix

In [124]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [126]:
mat1
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [127]:
mat1.shape

(5, 3)

In [128]:
mat2.shape

(5, 3)

In [129]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [130]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [131]:
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [132]:
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [133]:
mat1.T


array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [134]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [136]:
#creating mat3

In [137]:
mat3 = np.dot(mat1, mat2.T)

In [138]:
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [139]:
mat3.shape


(5, 5)

In [140]:
mat3.size

25

In [143]:
np.random.seed(0)
#number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))


In [144]:
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [146]:
weekly_sales = pd.DataFrame(sales_amounts,
                           index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almond butter", "Penut butter", "Cashew butter"])

In [147]:
weekly_sales


Almond butter  Penut butter  Cashew butter
Mon               12            15              0
Tues               3             3              7
Wed                9            19             18
Thurs              4             6             12
Fri                1             6              7

In [149]:
prices = np.array([10, 8, 12])

In [150]:
prices

array([10,  8, 12])

In [153]:
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                            index=["Price"],
                            columns=["Almond butter", "Penut butter", "Cashew butter"])

In [154]:
butter_prices

Almond butter  Penut butter  Cashew butter
Price             10             8             12

In [155]:
prices

array([10,  8, 12])

In [156]:
total_sales = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [157]:
#transposing to allow not equal shapes align

In [158]:
total_sales = prices.dot(sales_amounts.T)

In [159]:
total_sales

array([240, 138, 458, 232, 142])

In [161]:
butter_prices

Almond butter  Penut butter  Cashew butter
Price             10             8             12

In [162]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [163]:
weekly_sales


Almond butter  Penut butter  Cashew butter
Mon               12            15              0
Tues               3             3              7
Wed                9            19             18
Thurs              4             6             12
Fri                1             6              7

In [164]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [165]:
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [169]:
weekly_sales["Total ($)"] = daily_sales
weekly_sales

ValueError: Wrong number of items passed 5, placement implies 1

In [170]:
weekly_sales["Total ($)"] = daily_sales.T

In [171]:
weekly_sales

Almond butter  Penut butter  Cashew butter  Total ($)
Mon               12            15              0        240
Tues               3             3              7        138
Wed                9            19             18        458
Thurs              4             6             12        232
Fri                1             6              7        142