In [3]:
import numpy as np

Datatypes and Attributes

In [4]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
type(a2)

numpy.ndarray

In [8]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape


(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
import pandas as pd

In [18]:
df = pd.DataFrame(a2)

In [19]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [20]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [21]:
sample_array.dtype

dtype('int64')

In [22]:
ones = np.ones((2, 3))

In [23]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
ones.dtype

dtype('float64')

In [25]:
type(ones)

numpy.ndarray

In [26]:
zeros = np.zeros((2, 3))

In [27]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
range_array = np.arange(0, 10, 2)

In [29]:
range_array

array([0, 2, 4, 6, 8])

In [30]:
random_array = np.random.randint(0, 10, size=(3,5))

In [31]:
random_array

array([[3, 5, 5, 0, 3],
       [5, 2, 4, 3, 7],
       [0, 1, 5, 6, 1]])

In [32]:
random_array.size

15

In [33]:
random_array.shape

(3, 5)

In [34]:
np.random.random((5, 3))

array([[0.08008512, 0.68776257, 0.376516  ],
       [0.45798349, 0.08269742, 0.10552308],
       [0.36773405, 0.59869196, 0.99688762],
       [0.81406174, 0.99389399, 0.26007156],
       [0.78498948, 0.23622452, 0.98858604]])

In [35]:
random_array.shape

(3, 5)

In [36]:
np.random.seed()

In [37]:
random_array_3 = np.random.rand(5, 3)

In [38]:
random_array_3

array([[0.20157261, 0.0097699 , 0.48450037],
       [0.1620217 , 0.84562206, 0.53236426],
       [0.89719222, 0.60138697, 0.49607287],
       [0.05465528, 0.64211578, 0.82915456],
       [0.6171032 , 0.18479874, 0.22564022]])

In [39]:
random_array_3.size

15

In [40]:
random_array_3.shape

(5, 3)

In [41]:
type(random_array_3)

numpy.ndarray

In [42]:
# np.random.seed()
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4


array([[5, 4, 0],
       [6, 7, 6],
       [0, 6, 5],
       [5, 9, 1],
       [7, 9, 3]])

In [43]:
random_array_4.shape

(5, 3)

In [44]:
random_array_4.size

15

In [45]:
random_array_5 = np.random.random((5, 3))

In [46]:
random_array_5

array([[0.03726525, 0.98989959, 0.18090996],
       [0.96341016, 0.93593433, 0.89605785],
       [0.62676063, 0.49203807, 0.89255928],
       [0.35407324, 0.18674465, 0.7476148 ],
       [0.17371801, 0.1589243 , 0.44273732]])

In [47]:
random_array_5.shape

(5, 3)

In [48]:
random_array_5 = np.random.random((5, 3))

Viewing arrays

In [49]:
## viewing arrays and matrices 

In [50]:
 np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 7, 9])

In [51]:
random_array_99 = np.random.randint(999, size=(10,10))

In [52]:
random_array_99

array([[466, 463, 817, 188, 426, 491, 236, 642, 171, 930],
       [751, 726, 942, 570, 557, 444, 187, 935,  32, 836],
       [972, 310, 948, 637, 769, 190, 270, 567, 968, 186],
       [647, 539, 495, 573, 947, 633, 527, 370, 731, 463],
       [949, 971, 377, 695,   8, 489, 904, 556, 132, 596],
       [794, 974, 374, 714, 814, 180, 884, 875, 361,  47],
       [ 91, 791, 467, 516, 425, 971, 374, 238,  61, 290],
       [487, 899, 645, 824,  60, 992, 112, 422,   2, 969],
       [343, 439, 486, 214,  10,   8, 902, 862, 653, 397],
       [124,   9, 794, 973, 784, 487, 191, 553,  28, 507]])

In [53]:
np.unique(random_array_99())

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
np.unique([1,2,3,4,4,4,6])

In [ ]:
a1[0]

In [ ]:
a3.shape

In [ ]:
random_array_99.shape

In [ ]:
a3

In [ ]:
a2[1]

In [ ]:
 a4 = np.random.randint(10, size=(2,3,4,5))

In [ ]:
a4

In [ ]:
a4.shape, a4.ndim

In [ ]:
a4[:, :, :, :1]

In [ ]:
#4. manipulating and comparing arrays

arithmetic 

In [ ]:
a1 + ones


In [ ]:
ones = np.ones(3)

In [ ]:
ones

In [ ]:
a1 + ones

In [ ]:
a1 - ones

In [ ]:
a1 * a2

In [ ]:
a1

In [ ]:
a2

In [ ]:
a2 * a3

In [ ]:
np.reshape()

In [ ]:
a1 / ones

In [ ]:
a1 // a2

In [ ]:
a2 ** 2

In [ ]:
np.log(a1)

In [ ]:
listy_list = [1,2,3]

In [ ]:
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
np.sum(a1)

In [ ]:
massive_array = np.random.random(100000)

In [ ]:
massive_array[:10]

In [ ]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

In [ ]:
np.min(a2)

In [ ]:
np.var(a2)

In [ ]:
a2.T.shape

In [ ]:
a2.T


In [ ]:
a2.reshape()

In [ ]:
a2.reshape(2, 3, 1).shape

In [ ]:
a2.shape


In [ ]:
a2_reshape = a2.reshape(2,3,1)

In [ ]:
a2_reshape


In [ ]:
a2_reshape.size

In [ ]:
a2_reshape.shape

In [ ]:
a2_reshape * a3

In [ ]:
# how to transpose a matrix

In [ ]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [ ]:
mat1
mat2

In [ ]:
mat1.shape

In [ ]:
mat2.shape

In [ ]:
mat1

In [ ]:
mat2

In [ ]:
np.dot(mat1, mat2)

In [ ]:
np.dot(mat1, mat2)

In [ ]:
mat1.T


In [ ]:
mat1.shape, mat2.shape

In [ ]:
#creating mat3

In [ ]:
mat3 = np.dot(mat1, mat2.T)

In [ ]:
mat3

In [ ]:
mat3.shape


In [ ]:
mat3.size

In [ ]:
np.random.seed(0)
#number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))


In [ ]:
sales_amounts

In [ ]:
weekly_sales = pd.DataFrame(sales_amounts,
                           index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almond butter", "Penut butter", "Cashew butter"])

In [ ]:
weekly_sales


In [ ]:
prices = np.array([10, 8, 12])

In [ ]:
prices

In [ ]:
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                            index=["Price"],
                            columns=["Almond butter", "Penut butter", "Cashew butter"])

In [ ]:
butter_prices

In [ ]:
prices

In [ ]:
total_sales = prices.dot(sales_amounts)

In [ ]:
#transposing to allow not equal shapes align

In [ ]:
total_sales = prices.dot(sales_amounts.T)

In [ ]:
total_sales

In [ ]:
butter_prices

In [ ]:
butter_prices.shape, weekly_sales.shape

In [ ]:
weekly_sales


In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [ ]:
daily_sales

In [ ]:
weekly_sales["Total ($)"] = daily_sales
weekly_sales

In [ ]:
weekly_sales["Total ($)"] = daily_sales.T

In [ ]:
weekly_sales

Comparison operators

In [55]:
a1


array([1, 2, 3])

In [56]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [57]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [58]:
bool_array = a1 >= a2

In [59]:
bool_array


array([[ True,  True, False],
       [False, False, False]])

In [60]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [61]:
type(a2)

numpy.ndarray

In [63]:
import matplotlib.pyplot as plt

In [65]:
print(a2)

[[1.  2.  3.3]
 [4.  5.  6.5]]


In [67]:
random_array = np.random.randint(10, size=(3,5))

In [69]:
random_array


array([[3, 2, 6, 0, 8],
       [9, 1, 4, 9, 9],
       [7, 2, 1, 0, 0]])

In [70]:
np.sort(random_array)

array([[0, 2, 3, 6, 8],
       [1, 4, 9, 9, 9],
       [0, 0, 1, 2, 7]])

In [71]:
np.argsort(random_array)

array([[3, 1, 0, 2, 4],
       [1, 2, 0, 3, 4],
       [3, 4, 2, 1, 0]])

In [72]:
a1

array([1, 2, 3])

In [73]:
np.argsort(a1)

array([0, 1, 2])

In [74]:
np.argmin(a1)

0

In [75]:
np.argmax(a1)

2

In [76]:
np.argmax(random_array, axis=0)

array([1, 0, 0, 1, 1])

#practical example numpy in action

In [78]:
from matplotlib.image import imread

In [80]:
panda = imread("panda.png")

FileNotFoundError: [Errno 2] No such file or directory: 'panda.png'